---
apiVersion: v1
kind: Service
metadata:
  name: java-server
  namespace: local-k8s  # Add namespace
spec:
  type: ClusterIP
  selector:
    app: java-server
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-server
  namespace: local-k8s  # Add namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-server
  template:
    metadata:
      labels:
        app: java-server
    spec:
      containers:
        - name: java-server
          image: java-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9999