// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestConnection.proto

// Protobuf Java Version: 3.25.2
package com.jasper.test.grpc.grpcserver;

public final class TestConnection {
  private TestConnection() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TestRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jasper.test.grpc.grpcserver.TestRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
     * @return Whether the sendTimeStamp field is set.
     */
    boolean hasSendTimeStamp();
    /**
     * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
     * @return The sendTimeStamp.
     */
    com.google.protobuf.Timestamp getSendTimeStamp();
    /**
     * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
     */
    com.google.protobuf.TimestampOrBuilder getSendTimeStampOrBuilder();
  }
  /**
   * Protobuf type {@code com.jasper.test.grpc.grpcserver.TestRequest}
   */
  public static final class TestRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.jasper.test.grpc.grpcserver.TestRequest)
      TestRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TestRequest.newBuilder() to construct.
    private TestRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TestRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jasper.test.grpc.grpcserver.TestConnection.internal_static_com_jasper_test_grpc_grpcserver_TestRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jasper.test.grpc.grpcserver.TestConnection.internal_static_com_jasper_test_grpc_grpcserver_TestRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jasper.test.grpc.grpcserver.TestConnection.TestRequest.class, com.jasper.test.grpc.grpcserver.TestConnection.TestRequest.Builder.class);
    }

    private int bitField0_;
    public static final int SENDTIMESTAMP_FIELD_NUMBER = 1;
    private com.google.protobuf.Timestamp sendTimeStamp_;
    /**
     * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
     * @return Whether the sendTimeStamp field is set.
     */
    @java.lang.Override
    public boolean hasSendTimeStamp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
     * @return The sendTimeStamp.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getSendTimeStamp() {
      return sendTimeStamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sendTimeStamp_;
    }
    /**
     * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getSendTimeStampOrBuilder() {
      return sendTimeStamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sendTimeStamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getSendTimeStamp());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSendTimeStamp());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jasper.test.grpc.grpcserver.TestConnection.TestRequest)) {
        return super.equals(obj);
      }
      com.jasper.test.grpc.grpcserver.TestConnection.TestRequest other = (com.jasper.test.grpc.grpcserver.TestConnection.TestRequest) obj;

      if (hasSendTimeStamp() != other.hasSendTimeStamp()) return false;
      if (hasSendTimeStamp()) {
        if (!getSendTimeStamp()
            .equals(other.getSendTimeStamp())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSendTimeStamp()) {
        hash = (37 * hash) + SENDTIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getSendTimeStamp().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jasper.test.grpc.grpcserver.TestConnection.TestRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jasper.test.grpc.grpcserver.TestConnection.TestRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jasper.test.grpc.grpcserver.TestConnection.TestRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jasper.test.grpc.grpcserver.TestConnection.TestRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jasper.test.grpc.grpcserver.TestConnection.TestRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jasper.test.grpc.grpcserver.TestConnection.TestRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jasper.test.grpc.grpcserver.TestConnection.TestRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jasper.test.grpc.grpcserver.TestConnection.TestRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.jasper.test.grpc.grpcserver.TestConnection.TestRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.jasper.test.grpc.grpcserver.TestConnection.TestRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jasper.test.grpc.grpcserver.TestConnection.TestRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jasper.test.grpc.grpcserver.TestConnection.TestRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jasper.test.grpc.grpcserver.TestConnection.TestRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jasper.test.grpc.grpcserver.TestRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jasper.test.grpc.grpcserver.TestRequest)
        com.jasper.test.grpc.grpcserver.TestConnection.TestRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jasper.test.grpc.grpcserver.TestConnection.internal_static_com_jasper_test_grpc_grpcserver_TestRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jasper.test.grpc.grpcserver.TestConnection.internal_static_com_jasper_test_grpc_grpcserver_TestRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jasper.test.grpc.grpcserver.TestConnection.TestRequest.class, com.jasper.test.grpc.grpcserver.TestConnection.TestRequest.Builder.class);
      }

      // Construct using com.jasper.test.grpc.grpcserver.TestConnection.TestRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSendTimeStampFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        sendTimeStamp_ = null;
        if (sendTimeStampBuilder_ != null) {
          sendTimeStampBuilder_.dispose();
          sendTimeStampBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jasper.test.grpc.grpcserver.TestConnection.internal_static_com_jasper_test_grpc_grpcserver_TestRequest_descriptor;
      }

      @java.lang.Override
      public com.jasper.test.grpc.grpcserver.TestConnection.TestRequest getDefaultInstanceForType() {
        return com.jasper.test.grpc.grpcserver.TestConnection.TestRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.jasper.test.grpc.grpcserver.TestConnection.TestRequest build() {
        com.jasper.test.grpc.grpcserver.TestConnection.TestRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.jasper.test.grpc.grpcserver.TestConnection.TestRequest buildPartial() {
        com.jasper.test.grpc.grpcserver.TestConnection.TestRequest result = new com.jasper.test.grpc.grpcserver.TestConnection.TestRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.jasper.test.grpc.grpcserver.TestConnection.TestRequest result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.sendTimeStamp_ = sendTimeStampBuilder_ == null
              ? sendTimeStamp_
              : sendTimeStampBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jasper.test.grpc.grpcserver.TestConnection.TestRequest) {
          return mergeFrom((com.jasper.test.grpc.grpcserver.TestConnection.TestRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jasper.test.grpc.grpcserver.TestConnection.TestRequest other) {
        if (other == com.jasper.test.grpc.grpcserver.TestConnection.TestRequest.getDefaultInstance()) return this;
        if (other.hasSendTimeStamp()) {
          mergeSendTimeStamp(other.getSendTimeStamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getSendTimeStampFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Timestamp sendTimeStamp_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> sendTimeStampBuilder_;
      /**
       * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
       * @return Whether the sendTimeStamp field is set.
       */
      public boolean hasSendTimeStamp() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
       * @return The sendTimeStamp.
       */
      public com.google.protobuf.Timestamp getSendTimeStamp() {
        if (sendTimeStampBuilder_ == null) {
          return sendTimeStamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sendTimeStamp_;
        } else {
          return sendTimeStampBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
       */
      public Builder setSendTimeStamp(com.google.protobuf.Timestamp value) {
        if (sendTimeStampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sendTimeStamp_ = value;
        } else {
          sendTimeStampBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
       */
      public Builder setSendTimeStamp(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (sendTimeStampBuilder_ == null) {
          sendTimeStamp_ = builderForValue.build();
        } else {
          sendTimeStampBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
       */
      public Builder mergeSendTimeStamp(com.google.protobuf.Timestamp value) {
        if (sendTimeStampBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            sendTimeStamp_ != null &&
            sendTimeStamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getSendTimeStampBuilder().mergeFrom(value);
          } else {
            sendTimeStamp_ = value;
          }
        } else {
          sendTimeStampBuilder_.mergeFrom(value);
        }
        if (sendTimeStamp_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
       */
      public Builder clearSendTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sendTimeStamp_ = null;
        if (sendTimeStampBuilder_ != null) {
          sendTimeStampBuilder_.dispose();
          sendTimeStampBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
       */
      public com.google.protobuf.Timestamp.Builder getSendTimeStampBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSendTimeStampFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getSendTimeStampOrBuilder() {
        if (sendTimeStampBuilder_ != null) {
          return sendTimeStampBuilder_.getMessageOrBuilder();
        } else {
          return sendTimeStamp_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : sendTimeStamp_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getSendTimeStampFieldBuilder() {
        if (sendTimeStampBuilder_ == null) {
          sendTimeStampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getSendTimeStamp(),
                  getParentForChildren(),
                  isClean());
          sendTimeStamp_ = null;
        }
        return sendTimeStampBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.jasper.test.grpc.grpcserver.TestRequest)
    }

    // @@protoc_insertion_point(class_scope:com.jasper.test.grpc.grpcserver.TestRequest)
    private static final com.jasper.test.grpc.grpcserver.TestConnection.TestRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jasper.test.grpc.grpcserver.TestConnection.TestRequest();
    }

    public static com.jasper.test.grpc.grpcserver.TestConnection.TestRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestRequest>
        PARSER = new com.google.protobuf.AbstractParser<TestRequest>() {
      @java.lang.Override
      public TestRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TestRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.jasper.test.grpc.grpcserver.TestConnection.TestRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TestResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jasper.test.grpc.grpcserver.TestResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
     * @return Whether the sendTimeStamp field is set.
     */
    boolean hasSendTimeStamp();
    /**
     * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
     * @return The sendTimeStamp.
     */
    com.google.protobuf.Timestamp getSendTimeStamp();
    /**
     * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
     */
    com.google.protobuf.TimestampOrBuilder getSendTimeStampOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp receiveTimeStamp = 2;</code>
     * @return Whether the receiveTimeStamp field is set.
     */
    boolean hasReceiveTimeStamp();
    /**
     * <code>.google.protobuf.Timestamp receiveTimeStamp = 2;</code>
     * @return The receiveTimeStamp.
     */
    com.google.protobuf.Timestamp getReceiveTimeStamp();
    /**
     * <code>.google.protobuf.Timestamp receiveTimeStamp = 2;</code>
     */
    com.google.protobuf.TimestampOrBuilder getReceiveTimeStampOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp processTimeCost = 3;</code>
     * @return Whether the processTimeCost field is set.
     */
    boolean hasProcessTimeCost();
    /**
     * <code>.google.protobuf.Timestamp processTimeCost = 3;</code>
     * @return The processTimeCost.
     */
    com.google.protobuf.Timestamp getProcessTimeCost();
    /**
     * <code>.google.protobuf.Timestamp processTimeCost = 3;</code>
     */
    com.google.protobuf.TimestampOrBuilder getProcessTimeCostOrBuilder();
  }
  /**
   * Protobuf type {@code com.jasper.test.grpc.grpcserver.TestResponse}
   */
  public static final class TestResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.jasper.test.grpc.grpcserver.TestResponse)
      TestResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TestResponse.newBuilder() to construct.
    private TestResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TestResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jasper.test.grpc.grpcserver.TestConnection.internal_static_com_jasper_test_grpc_grpcserver_TestResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jasper.test.grpc.grpcserver.TestConnection.internal_static_com_jasper_test_grpc_grpcserver_TestResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jasper.test.grpc.grpcserver.TestConnection.TestResponse.class, com.jasper.test.grpc.grpcserver.TestConnection.TestResponse.Builder.class);
    }

    private int bitField0_;
    public static final int SENDTIMESTAMP_FIELD_NUMBER = 1;
    private com.google.protobuf.Timestamp sendTimeStamp_;
    /**
     * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
     * @return Whether the sendTimeStamp field is set.
     */
    @java.lang.Override
    public boolean hasSendTimeStamp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
     * @return The sendTimeStamp.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getSendTimeStamp() {
      return sendTimeStamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sendTimeStamp_;
    }
    /**
     * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getSendTimeStampOrBuilder() {
      return sendTimeStamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sendTimeStamp_;
    }

    public static final int RECEIVETIMESTAMP_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp receiveTimeStamp_;
    /**
     * <code>.google.protobuf.Timestamp receiveTimeStamp = 2;</code>
     * @return Whether the receiveTimeStamp field is set.
     */
    @java.lang.Override
    public boolean hasReceiveTimeStamp() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp receiveTimeStamp = 2;</code>
     * @return The receiveTimeStamp.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getReceiveTimeStamp() {
      return receiveTimeStamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : receiveTimeStamp_;
    }
    /**
     * <code>.google.protobuf.Timestamp receiveTimeStamp = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getReceiveTimeStampOrBuilder() {
      return receiveTimeStamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : receiveTimeStamp_;
    }

    public static final int PROCESSTIMECOST_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp processTimeCost_;
    /**
     * <code>.google.protobuf.Timestamp processTimeCost = 3;</code>
     * @return Whether the processTimeCost field is set.
     */
    @java.lang.Override
    public boolean hasProcessTimeCost() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp processTimeCost = 3;</code>
     * @return The processTimeCost.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getProcessTimeCost() {
      return processTimeCost_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : processTimeCost_;
    }
    /**
     * <code>.google.protobuf.Timestamp processTimeCost = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getProcessTimeCostOrBuilder() {
      return processTimeCost_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : processTimeCost_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getSendTimeStamp());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getReceiveTimeStamp());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(3, getProcessTimeCost());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSendTimeStamp());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getReceiveTimeStamp());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getProcessTimeCost());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jasper.test.grpc.grpcserver.TestConnection.TestResponse)) {
        return super.equals(obj);
      }
      com.jasper.test.grpc.grpcserver.TestConnection.TestResponse other = (com.jasper.test.grpc.grpcserver.TestConnection.TestResponse) obj;

      if (hasSendTimeStamp() != other.hasSendTimeStamp()) return false;
      if (hasSendTimeStamp()) {
        if (!getSendTimeStamp()
            .equals(other.getSendTimeStamp())) return false;
      }
      if (hasReceiveTimeStamp() != other.hasReceiveTimeStamp()) return false;
      if (hasReceiveTimeStamp()) {
        if (!getReceiveTimeStamp()
            .equals(other.getReceiveTimeStamp())) return false;
      }
      if (hasProcessTimeCost() != other.hasProcessTimeCost()) return false;
      if (hasProcessTimeCost()) {
        if (!getProcessTimeCost()
            .equals(other.getProcessTimeCost())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSendTimeStamp()) {
        hash = (37 * hash) + SENDTIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getSendTimeStamp().hashCode();
      }
      if (hasReceiveTimeStamp()) {
        hash = (37 * hash) + RECEIVETIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getReceiveTimeStamp().hashCode();
      }
      if (hasProcessTimeCost()) {
        hash = (37 * hash) + PROCESSTIMECOST_FIELD_NUMBER;
        hash = (53 * hash) + getProcessTimeCost().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jasper.test.grpc.grpcserver.TestConnection.TestResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jasper.test.grpc.grpcserver.TestConnection.TestResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jasper.test.grpc.grpcserver.TestConnection.TestResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jasper.test.grpc.grpcserver.TestConnection.TestResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jasper.test.grpc.grpcserver.TestConnection.TestResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jasper.test.grpc.grpcserver.TestConnection.TestResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jasper.test.grpc.grpcserver.TestConnection.TestResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jasper.test.grpc.grpcserver.TestConnection.TestResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.jasper.test.grpc.grpcserver.TestConnection.TestResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.jasper.test.grpc.grpcserver.TestConnection.TestResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jasper.test.grpc.grpcserver.TestConnection.TestResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jasper.test.grpc.grpcserver.TestConnection.TestResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jasper.test.grpc.grpcserver.TestConnection.TestResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jasper.test.grpc.grpcserver.TestResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jasper.test.grpc.grpcserver.TestResponse)
        com.jasper.test.grpc.grpcserver.TestConnection.TestResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jasper.test.grpc.grpcserver.TestConnection.internal_static_com_jasper_test_grpc_grpcserver_TestResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jasper.test.grpc.grpcserver.TestConnection.internal_static_com_jasper_test_grpc_grpcserver_TestResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jasper.test.grpc.grpcserver.TestConnection.TestResponse.class, com.jasper.test.grpc.grpcserver.TestConnection.TestResponse.Builder.class);
      }

      // Construct using com.jasper.test.grpc.grpcserver.TestConnection.TestResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSendTimeStampFieldBuilder();
          getReceiveTimeStampFieldBuilder();
          getProcessTimeCostFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        sendTimeStamp_ = null;
        if (sendTimeStampBuilder_ != null) {
          sendTimeStampBuilder_.dispose();
          sendTimeStampBuilder_ = null;
        }
        receiveTimeStamp_ = null;
        if (receiveTimeStampBuilder_ != null) {
          receiveTimeStampBuilder_.dispose();
          receiveTimeStampBuilder_ = null;
        }
        processTimeCost_ = null;
        if (processTimeCostBuilder_ != null) {
          processTimeCostBuilder_.dispose();
          processTimeCostBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jasper.test.grpc.grpcserver.TestConnection.internal_static_com_jasper_test_grpc_grpcserver_TestResponse_descriptor;
      }

      @java.lang.Override
      public com.jasper.test.grpc.grpcserver.TestConnection.TestResponse getDefaultInstanceForType() {
        return com.jasper.test.grpc.grpcserver.TestConnection.TestResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.jasper.test.grpc.grpcserver.TestConnection.TestResponse build() {
        com.jasper.test.grpc.grpcserver.TestConnection.TestResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.jasper.test.grpc.grpcserver.TestConnection.TestResponse buildPartial() {
        com.jasper.test.grpc.grpcserver.TestConnection.TestResponse result = new com.jasper.test.grpc.grpcserver.TestConnection.TestResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.jasper.test.grpc.grpcserver.TestConnection.TestResponse result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.sendTimeStamp_ = sendTimeStampBuilder_ == null
              ? sendTimeStamp_
              : sendTimeStampBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.receiveTimeStamp_ = receiveTimeStampBuilder_ == null
              ? receiveTimeStamp_
              : receiveTimeStampBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.processTimeCost_ = processTimeCostBuilder_ == null
              ? processTimeCost_
              : processTimeCostBuilder_.build();
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jasper.test.grpc.grpcserver.TestConnection.TestResponse) {
          return mergeFrom((com.jasper.test.grpc.grpcserver.TestConnection.TestResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jasper.test.grpc.grpcserver.TestConnection.TestResponse other) {
        if (other == com.jasper.test.grpc.grpcserver.TestConnection.TestResponse.getDefaultInstance()) return this;
        if (other.hasSendTimeStamp()) {
          mergeSendTimeStamp(other.getSendTimeStamp());
        }
        if (other.hasReceiveTimeStamp()) {
          mergeReceiveTimeStamp(other.getReceiveTimeStamp());
        }
        if (other.hasProcessTimeCost()) {
          mergeProcessTimeCost(other.getProcessTimeCost());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getSendTimeStampFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getReceiveTimeStampFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getProcessTimeCostFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Timestamp sendTimeStamp_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> sendTimeStampBuilder_;
      /**
       * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
       * @return Whether the sendTimeStamp field is set.
       */
      public boolean hasSendTimeStamp() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
       * @return The sendTimeStamp.
       */
      public com.google.protobuf.Timestamp getSendTimeStamp() {
        if (sendTimeStampBuilder_ == null) {
          return sendTimeStamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sendTimeStamp_;
        } else {
          return sendTimeStampBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
       */
      public Builder setSendTimeStamp(com.google.protobuf.Timestamp value) {
        if (sendTimeStampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sendTimeStamp_ = value;
        } else {
          sendTimeStampBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
       */
      public Builder setSendTimeStamp(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (sendTimeStampBuilder_ == null) {
          sendTimeStamp_ = builderForValue.build();
        } else {
          sendTimeStampBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
       */
      public Builder mergeSendTimeStamp(com.google.protobuf.Timestamp value) {
        if (sendTimeStampBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            sendTimeStamp_ != null &&
            sendTimeStamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getSendTimeStampBuilder().mergeFrom(value);
          } else {
            sendTimeStamp_ = value;
          }
        } else {
          sendTimeStampBuilder_.mergeFrom(value);
        }
        if (sendTimeStamp_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
       */
      public Builder clearSendTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sendTimeStamp_ = null;
        if (sendTimeStampBuilder_ != null) {
          sendTimeStampBuilder_.dispose();
          sendTimeStampBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
       */
      public com.google.protobuf.Timestamp.Builder getSendTimeStampBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSendTimeStampFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getSendTimeStampOrBuilder() {
        if (sendTimeStampBuilder_ != null) {
          return sendTimeStampBuilder_.getMessageOrBuilder();
        } else {
          return sendTimeStamp_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : sendTimeStamp_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp sendTimeStamp = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getSendTimeStampFieldBuilder() {
        if (sendTimeStampBuilder_ == null) {
          sendTimeStampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getSendTimeStamp(),
                  getParentForChildren(),
                  isClean());
          sendTimeStamp_ = null;
        }
        return sendTimeStampBuilder_;
      }

      private com.google.protobuf.Timestamp receiveTimeStamp_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> receiveTimeStampBuilder_;
      /**
       * <code>.google.protobuf.Timestamp receiveTimeStamp = 2;</code>
       * @return Whether the receiveTimeStamp field is set.
       */
      public boolean hasReceiveTimeStamp() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp receiveTimeStamp = 2;</code>
       * @return The receiveTimeStamp.
       */
      public com.google.protobuf.Timestamp getReceiveTimeStamp() {
        if (receiveTimeStampBuilder_ == null) {
          return receiveTimeStamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : receiveTimeStamp_;
        } else {
          return receiveTimeStampBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp receiveTimeStamp = 2;</code>
       */
      public Builder setReceiveTimeStamp(com.google.protobuf.Timestamp value) {
        if (receiveTimeStampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          receiveTimeStamp_ = value;
        } else {
          receiveTimeStampBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp receiveTimeStamp = 2;</code>
       */
      public Builder setReceiveTimeStamp(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (receiveTimeStampBuilder_ == null) {
          receiveTimeStamp_ = builderForValue.build();
        } else {
          receiveTimeStampBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp receiveTimeStamp = 2;</code>
       */
      public Builder mergeReceiveTimeStamp(com.google.protobuf.Timestamp value) {
        if (receiveTimeStampBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            receiveTimeStamp_ != null &&
            receiveTimeStamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getReceiveTimeStampBuilder().mergeFrom(value);
          } else {
            receiveTimeStamp_ = value;
          }
        } else {
          receiveTimeStampBuilder_.mergeFrom(value);
        }
        if (receiveTimeStamp_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp receiveTimeStamp = 2;</code>
       */
      public Builder clearReceiveTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        receiveTimeStamp_ = null;
        if (receiveTimeStampBuilder_ != null) {
          receiveTimeStampBuilder_.dispose();
          receiveTimeStampBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp receiveTimeStamp = 2;</code>
       */
      public com.google.protobuf.Timestamp.Builder getReceiveTimeStampBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getReceiveTimeStampFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp receiveTimeStamp = 2;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getReceiveTimeStampOrBuilder() {
        if (receiveTimeStampBuilder_ != null) {
          return receiveTimeStampBuilder_.getMessageOrBuilder();
        } else {
          return receiveTimeStamp_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : receiveTimeStamp_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp receiveTimeStamp = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getReceiveTimeStampFieldBuilder() {
        if (receiveTimeStampBuilder_ == null) {
          receiveTimeStampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getReceiveTimeStamp(),
                  getParentForChildren(),
                  isClean());
          receiveTimeStamp_ = null;
        }
        return receiveTimeStampBuilder_;
      }

      private com.google.protobuf.Timestamp processTimeCost_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> processTimeCostBuilder_;
      /**
       * <code>.google.protobuf.Timestamp processTimeCost = 3;</code>
       * @return Whether the processTimeCost field is set.
       */
      public boolean hasProcessTimeCost() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp processTimeCost = 3;</code>
       * @return The processTimeCost.
       */
      public com.google.protobuf.Timestamp getProcessTimeCost() {
        if (processTimeCostBuilder_ == null) {
          return processTimeCost_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : processTimeCost_;
        } else {
          return processTimeCostBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp processTimeCost = 3;</code>
       */
      public Builder setProcessTimeCost(com.google.protobuf.Timestamp value) {
        if (processTimeCostBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          processTimeCost_ = value;
        } else {
          processTimeCostBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp processTimeCost = 3;</code>
       */
      public Builder setProcessTimeCost(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (processTimeCostBuilder_ == null) {
          processTimeCost_ = builderForValue.build();
        } else {
          processTimeCostBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp processTimeCost = 3;</code>
       */
      public Builder mergeProcessTimeCost(com.google.protobuf.Timestamp value) {
        if (processTimeCostBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            processTimeCost_ != null &&
            processTimeCost_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getProcessTimeCostBuilder().mergeFrom(value);
          } else {
            processTimeCost_ = value;
          }
        } else {
          processTimeCostBuilder_.mergeFrom(value);
        }
        if (processTimeCost_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp processTimeCost = 3;</code>
       */
      public Builder clearProcessTimeCost() {
        bitField0_ = (bitField0_ & ~0x00000004);
        processTimeCost_ = null;
        if (processTimeCostBuilder_ != null) {
          processTimeCostBuilder_.dispose();
          processTimeCostBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp processTimeCost = 3;</code>
       */
      public com.google.protobuf.Timestamp.Builder getProcessTimeCostBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getProcessTimeCostFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp processTimeCost = 3;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getProcessTimeCostOrBuilder() {
        if (processTimeCostBuilder_ != null) {
          return processTimeCostBuilder_.getMessageOrBuilder();
        } else {
          return processTimeCost_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : processTimeCost_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp processTimeCost = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getProcessTimeCostFieldBuilder() {
        if (processTimeCostBuilder_ == null) {
          processTimeCostBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getProcessTimeCost(),
                  getParentForChildren(),
                  isClean());
          processTimeCost_ = null;
        }
        return processTimeCostBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.jasper.test.grpc.grpcserver.TestResponse)
    }

    // @@protoc_insertion_point(class_scope:com.jasper.test.grpc.grpcserver.TestResponse)
    private static final com.jasper.test.grpc.grpcserver.TestConnection.TestResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jasper.test.grpc.grpcserver.TestConnection.TestResponse();
    }

    public static com.jasper.test.grpc.grpcserver.TestConnection.TestResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestResponse>
        PARSER = new com.google.protobuf.AbstractParser<TestResponse>() {
      @java.lang.Override
      public TestResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TestResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.jasper.test.grpc.grpcserver.TestConnection.TestResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  /**
   * Protobuf service {@code com.jasper.test.grpc.grpcserver.GRPCTestService}
   */
  public static abstract class GRPCTestService
      implements com.google.protobuf.Service {
    protected GRPCTestService() {}

    public interface Interface {
      /**
       * <code>rpc testConnectionTimeCost(.com.jasper.test.grpc.grpcserver.TestRequest) returns (.com.jasper.test.grpc.grpcserver.TestResponse);</code>
       */
      public abstract void testConnectionTimeCost(
          com.google.protobuf.RpcController controller,
          com.jasper.test.grpc.grpcserver.TestConnection.TestRequest request,
          com.google.protobuf.RpcCallback<com.jasper.test.grpc.grpcserver.TestConnection.TestResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new GRPCTestService() {
        @java.lang.Override
        public  void testConnectionTimeCost(
            com.google.protobuf.RpcController controller,
            com.jasper.test.grpc.grpcserver.TestConnection.TestRequest request,
            com.google.protobuf.RpcCallback<com.jasper.test.grpc.grpcserver.TestConnection.TestResponse> done) {
          impl.testConnectionTimeCost(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.testConnectionTimeCost(controller, (com.jasper.test.grpc.grpcserver.TestConnection.TestRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.jasper.test.grpc.grpcserver.TestConnection.TestRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.jasper.test.grpc.grpcserver.TestConnection.TestResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc testConnectionTimeCost(.com.jasper.test.grpc.grpcserver.TestRequest) returns (.com.jasper.test.grpc.grpcserver.TestResponse);</code>
     */
    public abstract void testConnectionTimeCost(
        com.google.protobuf.RpcController controller,
        com.jasper.test.grpc.grpcserver.TestConnection.TestRequest request,
        com.google.protobuf.RpcCallback<com.jasper.test.grpc.grpcserver.TestConnection.TestResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.jasper.test.grpc.grpcserver.TestConnection.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.testConnectionTimeCost(controller, (com.jasper.test.grpc.grpcserver.TestConnection.TestRequest)request,
            com.google.protobuf.RpcUtil.<com.jasper.test.grpc.grpcserver.TestConnection.TestResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.jasper.test.grpc.grpcserver.TestConnection.TestRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.jasper.test.grpc.grpcserver.TestConnection.TestResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.jasper.test.grpc.grpcserver.TestConnection.GRPCTestService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void testConnectionTimeCost(
          com.google.protobuf.RpcController controller,
          com.jasper.test.grpc.grpcserver.TestConnection.TestRequest request,
          com.google.protobuf.RpcCallback<com.jasper.test.grpc.grpcserver.TestConnection.TestResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.jasper.test.grpc.grpcserver.TestConnection.TestResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.jasper.test.grpc.grpcserver.TestConnection.TestResponse.class,
            com.jasper.test.grpc.grpcserver.TestConnection.TestResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.jasper.test.grpc.grpcserver.TestConnection.TestResponse testConnectionTimeCost(
          com.google.protobuf.RpcController controller,
          com.jasper.test.grpc.grpcserver.TestConnection.TestRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.jasper.test.grpc.grpcserver.TestConnection.TestResponse testConnectionTimeCost(
          com.google.protobuf.RpcController controller,
          com.jasper.test.grpc.grpcserver.TestConnection.TestRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.jasper.test.grpc.grpcserver.TestConnection.TestResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.jasper.test.grpc.grpcserver.TestConnection.TestResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:com.jasper.test.grpc.grpcserver.GRPCTestService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jasper_test_grpc_grpcserver_TestRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jasper_test_grpc_grpcserver_TestRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jasper_test_grpc_grpcserver_TestResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jasper_test_grpc_grpcserver_TestResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024TestConnection.proto\022\037com.jasper.test." +
      "grpc.grpcserver\032\036google/protobuf/wrapper" +
      "s.proto\032\037google/protobuf/timestamp.proto" +
      "\"@\n\013TestRequest\0221\n\rsendTimeStamp\030\001 \001(\0132\032" +
      ".google.protobuf.Timestamp\"\254\001\n\014TestRespo" +
      "nse\0221\n\rsendTimeStamp\030\001 \001(\0132\032.google.prot" +
      "obuf.Timestamp\0224\n\020receiveTimeStamp\030\002 \001(\013" +
      "2\032.google.protobuf.Timestamp\0223\n\017processT" +
      "imeCost\030\003 \001(\0132\032.google.protobuf.Timestam" +
      "p2\210\001\n\017GRPCTestService\022u\n\026testConnectionT" +
      "imeCost\022,.com.jasper.test.grpc.grpcserve" +
      "r.TestRequest\032-.com.jasper.test.grpc.grp" +
      "cserver.TestResponseB&\n\037com.jasper.test." +
      "grpc.grpcserverP\000\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_jasper_test_grpc_grpcserver_TestRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_jasper_test_grpc_grpcserver_TestRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jasper_test_grpc_grpcserver_TestRequest_descriptor,
        new java.lang.String[] { "SendTimeStamp", });
    internal_static_com_jasper_test_grpc_grpcserver_TestResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_jasper_test_grpc_grpcserver_TestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jasper_test_grpc_grpcserver_TestResponse_descriptor,
        new java.lang.String[] { "SendTimeStamp", "ReceiveTimeStamp", "ProcessTimeCost", });
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
